### ISSUE TITLE
Help Me with this issue

### ISSUE THREAD

**Issue by rokyj2021** [ayushteke/magneto_HEROKU#2]
2021-07-15T05:05:07.000000+00:00 app[api]: Build started by user rokyj220@gmail.com
2021-07-15T05:09:43.000000+00:00 app[api]: Build succeeded
2021-07-15T05:09:43.691101+00:00 app[api]: Deployed worker (c780fbd2f81e) by user rokyj220@gmail.com
2021-07-15T05:09:43.691101+00:00 app[api]: Release v7 created by user rokyj220@gmail.com
2021-07-15T05:09:44.590838+00:00 app[api]: Scaled to worker@1:Free by user rokyj220@gmail.com
2021-07-15T05:10:12.566948+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c bash\ start.sh`
2021-07-15T05:10:13.297322+00:00 heroku[worker.1]: State changed from starting to up
2021-07-15T05:10:13.305048+00:00 heroku[worker.1]: Idling
2021-07-15T05:10:13.309098+00:00 heroku[worker.1]: State changed from up to down
2021-07-15T05:10:13.317924+00:00 heroku[worker.1]: Idling because quota is exhausted
2021-07-15T05:10:55.176481+00:00 heroku[worker.1]: State changed from down to starting
2021-07-15T05:11:18.760895+00:00 app[worker.1]: 2021-07-15 05:11:18,760 - bot - ERROR - could not translate host name "ec2-34-254-69-72.eu-west-1.compute.amazonaws.com" to address: Temporary failure in name resolution
2021-07-15T05:11:18.760928+00:00 app[worker.1]: 
2021-07-15T05:11:18.760971+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-15T05:11:18.761016+00:00 app[worker.1]:   File "/usr/src/app/bot/__init__.py", line 110, in <module>
2021-07-15T05:11:18.761292+00:00 app[worker.1]:     conn = psycopg2.connect(DB_URI)
2021-07-15T05:11:18.761300+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
2021-07-15T05:11:18.761506+00:00 app[worker.1]:     conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
2021-07-15T05:11:18.761553+00:00 app[worker.1]: psycopg2.OperationalError: could not translate host name "ec2-34-254-69-72.eu-west-1.compute.amazonaws.com" to address: Temporary failure in name resolution
2021-07-15T05:11:18.761554+00:00 app[worker.1]: 
2021-07-15T05:11:18.761559+00:00 app[worker.1]: 
2021-07-15T05:11:18.761559+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2021-07-15T05:11:18.761560+00:00 app[worker.1]: 
2021-07-15T05:11:18.761560+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-15T05:11:18.761608+00:00 app[worker.1]:   File "/usr/src/app/bot/__init__.py", line 124, in <module>
2021-07-15T05:11:18.761783+00:00 app[worker.1]:     exit(1)
2021-07-15T05:11:18.761787+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/_sitebuiltins.py", line 26, in __call__
2021-07-15T05:11:18.761949+00:00 app[worker.1]:     raise SystemExit(code)
2021-07-15T05:11:18.761953+00:00 app[worker.1]: SystemExit: 1
2021-07-15T05:11:18.761975+00:00 app[worker.1]: 
2021-07-15T05:11:18.761976+00:00 app[worker.1]: During handling of the above exception, another exception occurred:
2021-07-15T05:11:18.761976+00:00 app[worker.1]: 
2021-07-15T05:11:18.768127+00:00 app[worker.1]: Traceback (most recent call last):
2021-07-15T05:11:18.768170+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 188, in _run_module_as_main
2021-07-15T05:11:18.768599+00:00 app[worker.1]:     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
2021-07-15T05:11:18.768710+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 147, in _get_module_details
2021-07-15T05:11:18.769047+00:00 app[worker.1]:     return _get_module_details(pkg_main_name, error)
2021-07-15T05:11:18.769270+00:00 app[worker.1]:   File "/usr/local/lib/python3.9/runpy.py", line 111, in _get_module_details
2021-07-15T05:11:18.769533+00:00 app[worker.1]:     __import__(pkg_name)
2021-07-15T05:11:18.769638+00:00 app[worker.1]:   File "/usr/src/app/bot/__init__.py", line 126, in <module>
2021-07-15T05:11:18.769990+00:00 app[worker.1]:     cur.close()
2021-07-15T05:11:18.770119+00:00 app[worker.1]: NameError: name 'cur' is not defined
2021-07-15T05:11:19.757052+00:00 heroku[worker.1]: Starting process with command `/bin/sh -c bash\ start.sh`
2021-07-15T05:11:20.442575+00:00 heroku[worker.1]: State changed from starting to up
2021-07-15T05:11:20.451198+00:00 heroku[worker.1]: Idling
2021-07-15T05:11:20.537657+00:00 heroku[worker.1]: State changed from up to down
2021-07-15T05:11:20.578426+00:00 heroku[worker.1]: Idling because quota is exhausted

**Comment by rokyj2021** [comment]
I
